@startuml buffered-file-syncer-activity-diagram

title Buffered File Syncer Activity Diagram

start

:Set <b>prev</b> to empty/non existing;

repeat

    partition Update {

        if (local == prev) then (yes)
            if (remote == prev) then (yes)
                :do nothing;
            else (no)
                :pull remote;
            endif
        else (no)
            if (remote == prev) then (yes)
                :push local;
            else (no)
                #palegreen:<b>resolver.resolve()</b>;
                note right
                Custom
                endnote
            endif   
        endif

    :Save file state to <b>prev</b>;

    }

:Wait syncinterval;

repeat while (stopSyncing) is (no)
->yes;

stop

@enduml